ARG NODE_VERSION=20.18.1

FROM node:${NODE_VERSION}-alpine as base

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy app
COPY . .

# Build the app
ARG GOOGLE_SPREADSHEET_ID
ARG GOOGLE_SERVICE_ACCOUNT_EMAIL
ARG GOOGLE_PRIVATE_KEY
ARG GOOGLE_SHEET_NAME
ARG GOOGLE_SHEET_RANGE
ARG WHATSAPP_BUSINESS_NUMBER

ENV GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
ENV GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
ENV GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
ENV GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME}
ENV GOOGLE_SHEET_RANGE=${GOOGLE_SHEET_RANGE}
ENV NEXT_PUBLIC_WHATSAPP_BUSINESS_NUMBER=${WHATSAPP_BUSINESS_NUMBER}

##RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev"]